- README.md
I have prepared an AUR package for Arch.
> Add installation notes for Arch Linux

- README.md
added thermald hint to readme. If it is running it will throttle the CPU quite hard when it gets over 80°C. stopping/disabling it will do the trick.
Do you think this is the correct position for it or do you want a FAQ/Troubleshoot section?
> added thermald hint to readme

- README.md
- etc/lenovo_fix.conf
- lenovo_fix.py
> Improvement/configure cTDP

- README.md
yaourt has many security issues, but being one of the most well known people keep using it...replacing with an improved AUR helper.
> Different AUR helper in README

- README.md
- lenovo_fix.py
Based on https://github.com/erpalma/lenovo-throttling-fix/issues/64
Two minor changes:
1. Update debug error message
2. Update readme MSR section
> Update MSR access restriction message

- README.md
> Missing Debian/Ubuntu python3-wheel dep

- README.md
> New model added

- README.md
- install.sh
- runit/lenovo_fix/run
Added Void Linux/Runit instructions to README.rst, changed install script to recognize when to run systemd/runit specific commands, added runit service directory (runit/lenovo_fix)
> added void/runit support

- README.md
> Add copr repository instructions for Fedora

- README.md
On systems where the EC doesn't reset the values
(ex: ASUS Zenbook UX430UNR), it is probably prefered to use the
official intel_rapl driver.
> Mention the official intel_rapl driver

- README.md
- etc/lenovo_fix.conf
- lenovo_fix.py
Implements a similar feature found on ThrottleStop. Also, solves issue 163 (https://github.com/erpalma/throttled/issues/163)
This is my first PR for throttled, so I hope the code is in order.
> Implement "Disable BDPROCHOT"

- README.md
- install.sh
- openrc/lenovo_fix
- package/PKGBUILD
Hi there! I added an init script for OpenRC and support with install.sh. Love this program its fantastic and it having OpenRC support just makes it even better for me :) and hopefully anyone else on Artix Linux for example.
> Add OpenRC support

- README.md
> Added A word about manufacturer provided tooling

- README.md
> Added documentation on how to disable Kernel Lockdown

- lenovo_fix.py
Adds the ability to restore HWP mode to 'default', not currently possible - requiring a reboot
'Default' being setting the x86_energy_perf_policy EPP to 128 i.e. default / normal / balance-performance - depending on the existing EPB
> Ability to restore HWP mode to 'default'

- README.md
> Add note about MSR writes in kernel >=5.9

- lenovo_fix.py
This adds the CPU identifier used by i7-10875H.
> Adds more Comet Lake identifiers

- README.md
Thank you very much for sharing this fix! I can confirm it helped with a T14 Gen 1
https://pcsupport.lenovo.com/de/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t14-type-20ud-20ue
> Adds T14 to list of tested hardware in README.md

- README.md
Tested on Lenovo T470s (20HG).
> Update README.md: add T470s to the list of tested hardware

- README.md
I've used this tool on my X1 Carbon Gen 8 and it has worked exactly as described.
> Add X1C8 to the tested hardware list in README.md

- install.sh
- throttled.py
Fixed a small issue in the install script, and added the CPUID of my variant of the Tiger Lake mobile CPU.
> Support Tiger Lake mobile CPU

- README.md
Replace the legacy name by the new one.
> Replace lenovo_fix by throttled in README.md

- README.md
I am able to confirm that `throttled` works on the X390. 
Prior to using `throttled` sometimes my PC would inexplicably (at the time, now I learn it is due to "lap detection"??) throttle itself, and from observing temps I would see it would adjust clocks as needed to never exceed 50C (probably "lap safe" temperature).
Since I use the Thinkpad Ultra Dock, the airflow is already quite bad, so at 50C throttle it is borderline unusable.
Thanks to `throttled` I can bypass it and keep using my laptop :)
Other specs if relevant:
```
-`                    raghu@arch
.o+`                   ----------
`ooo/                   OS: Arch Linux x86_64
`+oooo:                  Host: 20Q0S05E00 ThinkPad X390
`+oooooo:                 Kernel: 6.0.10-arch2-1
-+oooooo+:                Uptime: 1 day, 6 hours, …
```
> Document support for X390

- throttled.py
On some systems, the name of the battery or the adapter may be different. The code assumes the adapter is called "line_power_AC" and the battery "BAT0" but in my system both are different.
UPower has the OnBattery property which we can query and this is more robust. Additionally, we can do it directly throuth the dbus API without invoking a sub-process.
> Query UPower's OnBattery property directly.
