README.md

Fix typos in the install command for openSUSE
The dependencies given to zypper had 2 typos in them which prevented the
dependencies dbus-1-glib-devel and python3-devel from installing when running the zypper command stated in the README.

Fix typos in the install command for openSUSE.

---

README.md

To have `./install.sh` run successfully I also needed to install package python3-devel on my Fedora 28 installation.

Fedora: package python3-devel is also required

---

README.md

Adds a missing package needed in Fedora 29.  Checked that is is present in F28 as well.  Also cleaned up trailing whitespace (editor)

Add python3-virtualenv package to fedora install procedure

---

README.md
install.sh

Since Python 3.3 venv is part of the standard library, replacing virtualenv. Since 3.5 the recommended way to create a venv is `python3 -m venv <path>`, all actively developed distributions have at least 3.5 (even centos epel ;) ).
https://docs.python.org/3/library/venv.html

use builtin venv

---

install.sh

If the Git repository is checked out to `/opt/lenovo_fix`, the `install.sh` script will fail with the following error:
```
cp: 'requirements.txt' and '/opt/lenovo_fix/requirements.txt' are the same file
cp: 'lenovo_fix.py' and '/opt/lenovo_fix/lenovo_fix.py' are the same file
cp: 'mmio.py' and '/opt/lenovo_fix/mmio.py' are the same file
```
Change the `cp` to `cp -n` will prevent this.

do not overwrite an existing file

---

README.md

In default Fedora installation (28/29) GNU make is missing by default. You need to install it before running `install.sh`

GNU Make is missing

---

README.md

Add the missing dependency python3-venv to the debian instructions

Update README.md: add python3-venv for debian

---

README.md

Sorry for a pedantic change.
I noticed while setting this up again recently that I couldn't just copy and paste the commands since `dnf` was not prefixed with `sudo`.
I'm hoping to contribute to this project a bit if I get a chance.

readme: Prefix package install commands with sudo.

---

README.md

The static fix (with intel_rapl) uses a lot of space, but does not actually relate to throttled. I've moved the static-fix to the bottom of the ReadMe, so it is still available, but doesn't take the space up top.

Update Readme to remove static-fix from top

---

README.md

I'm using this fix successfully since ~6 month on my Lenovo L490 with these stable settings:
```
[GENERAL]
Enabled: True
Sysfs_Power_Path: /sys/class/power_supply/AC*/online
[BATTERY]
Update_Rate_s: 30
PL1_Tdp_W: 29
PL1_Duration_s: 28
PL2_Tdp_W: 44
PL2_Duration_S: 0.002
Trip_Temp_C: 85
cTDP: 0
Disable_BDPROCHOT: False
[AC]
Update_Rate_s: 5
PL1_Tdp_W: 44
PL1_Duration_s: 28
PL2_Tdp_W: 44
PL2_Duration_S: 0.002
Trip_Temp_C: 95
HWP_Mode: True
cTDP: 2
Disable_BDPROCHOT: False
[UNDERVOLT.BATTERY]
CORE: -100
GPU: -70
CACHE: -100
UNCORE: -70
ANALOGIO: 0
[UNDERVOLT.AC]
CORE: -110
GPU: -80
CACHE: -110
UNCORE: -80
ANALOGIO: 0
```
Before I applied this fix, under heavy load my CPU frequency was throttled down to under 1 GHz and the fan was never activated. Now I get 3.3GHz under full cpu load - 3 …

Add Lenovo L490 to the supported devices

---

README.md
etc/lenovo_fix.conf
lenovo_fix.py

Currently reloading changes to the config requires restarting the service.
This change reloads the config if it's been modified (as determined by the last modified time of the file), unless the file no longer exists.

Reload when modified

---

systemd/lenovo_fix.service

`StandardError` and `StandardOutput` don't support `syslog` anymore (they're long gone from the systemd manpages), and since 246, are migrated to `journal` under the hood.
As `journal` is also the default, don't configure it explicitly at all.
Related: https://github.com/NixOS/nixpkgs/pull/95353

lenovo_fix.service: Don't use deprecated logging options anymore

---

README.md

Replaces `lenovo-throttling-fix` with `throttled` since it looks like the GitHub repo moved. While the old remote links work, curious folks (like me!) might see that and think they are downloading code from a different repository, and be hesitant to run it.

README: Update GitHub repo links

---

README.md

I removed the command to add the overlay, this is documented in the overlay repository.
Also added instructions for OpenRC, which is more often used that SystemD with Gentoo.

Update installation instructions for Gentoo

---

package/PKGBUILD

Performing renaming from `lenovo_fix` to `throttled` on ArchLinux.

---

install.sh
openrc/throttled

This maintains consistency with the install.sh script by using the virtualenv that the script sets up. The original version was using a different interpreter and complained about missing imports. Additionally, the new shebang now points to the correct openrc-run executable. These were the only changes needed for this script to work on Gentoo.

openrc fix

---

install.sh

This fixes a problem with my recent commit. I used `[ "$INIT" == "systemd" ]` (and similar), which works in bash, but not in `/usr/bin/sh`. I changed it to `[ "$INIT" = "systemd" ]` (and similar) to correct this issue.

compatability with non-bash /bin/sh symlinks

---

README.md

Adds missing requirement to  run `sudo ./throttled/install.sh successfully.`

Add python3-cairo-dev as requirement for ubuntu (21.10)

---

README.md

This commit adds the installation instructions for Alpine Linux to the README. See [the package](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/throttled).

add alpine linux package to README

---

throttled.py

Added LunarLake definition, it finally helped to make "Balanced" profile usable on my X1 Carbon Gen 13.
Before running throttled, only Power Save and Performance profiles were working as expected. Under Balanced profile CPU will stuck at 400 MHz no matter what.
Only thing I've changed in configuration is Disable_BDPROCHOT (True), BTW.

Added LunarLake definition
